const corpsList = [
  "Ankara Büyükşehir Belediyesi",
  "Udentify",
  "Netigma",
  "Toprak Mahsulleri Ofisi",
  "AFAD",
  "Emlak GYO",
  "Doğanay WMS",
  "Kare Lojistik",
  "Emlak İnşaat",
  "Ankara Büyükşehir Belediyesi",
  "Udentify",
  "Netigma",
  "Toprak Mahsulleri Ofisi",
  "AFAD",
  "Emlak GYO",
  "Doğanay WMS",
  "Kare Lojistik",
  "Emlak İnşaat",
];
